spring:
  application:
    name: fundtransfer
#Postgres db properties
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: kiran
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#health exposer
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - gateway
          - routes
          - mappings
          - env

  endpoint:
    health:
      show-details: when_authorized

  metrics:
    tags:
      application: ${spring.application.name}